/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutosaveText: typeof import('./components/common/AutosaveText.vue')['default']
    ColorOptions: typeof import('./components/common/ColorOptions.vue')['default']
    ColorPicker: typeof import('./components/common/ColorPicker.vue')['default']
    EmbeddedMap: typeof import('./components/locations/EmbeddedMap.vue')['default']
    ErrorHint: typeof import('./components/common/ErrorHint.vue')['default']
    LayersPanels: typeof import('./components/locations/LayersPanels.vue')['default']
    PhotoDetail: typeof import('./components/photos/PhotoDetail.vue')['default']
    PhotoGrid: typeof import('./components/photos/PhotoGrid.vue')['default']
    PhotoIcon: typeof import('./components/photos/PhotoIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortedCombo: typeof import('./components/common/SortedCombo.vue')['default']
    TagGraph: typeof import('./components/tags/TagGraph.vue')['default']
    TagInput: typeof import('./components/tags/TagInput.vue')['default']
  }
}
