/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutosaveText: typeof import('./components/AutosaveText.vue')['default']
    ColorOptions: typeof import('./components/ColorOptions.vue')['default']
    ColorPicker: typeof import('./components/ColorPicker.vue')['default']
    PhotoDetail: typeof import('./components/PhotoDetail.vue')['default']
    PhotoGrid: typeof import('./components/PhotoGrid.vue')['default']
    PhotoIcon: typeof import('./components/PhotoIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SortedCombo: typeof import('./components/SortedCombo.vue')['default']
    TagInput: typeof import('./components/TagInput.vue')['default']
  }
}
